### ISSUE TITLE
Citing

### ISSUE THREAD

**Issue by garciagenrique** [singularityhub/singularity-ci#9]
Hi @vsoch,

Thanks for developing and sharing these libraries ! I found them super instructive and easy to use ! :) 

I am indeed implementing the gitlab-ci that you have developed in a project (also open source), so I was wondering which is the correct way to cite you / your repo. The project is another "template project" in where I am showing how to create a CI/CD to the Zenodo repository using and adapting your code an others (also OS). I have already changed the license type (MIT is more restrictive if I am not wrong - although need to keep investigating this). But I will like to point to your tutorial/depo in the readme so the people can see where the original code comes from. 

Thanks in any case in advance.

Cheers,

**Comment by vsoch** [comment]
The tutorial here and the code for the CI have different licenses (probably not ideal) but that's what it looks like. There are actually two different issues here - citation (which I can create a zenodo archive to make easy to do) and then actually using the code (which you can't just slap an MIT license on, for reasons discussed below).

> I have already changed the license type (MIT is more restrictive if I am not wrong - although need to keep investigating this). But I will like to point to your tutorial/depo in the readme so the people can see where the original code comes from.

So, you technically can't just to decide to change a license like that. For the tutorials - AGPL is actually far more restrictive - https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0) - you would need to have any derivatives also released under AGPL, and made totally public. It's one that I choose when I want something to remain completely open source. 

For the gitlab-ci - BSD3, it is also more restrictive than MIT.

> BSD-licensed projects can be used/redistributed in MIT-licensed projects. FALSE MIT license allows for distribution without contribution credits; BSD doesn't.

So if you start with the code you need to always include the original license, you can read the three points verbatim [here](https://gitlab.com/singularityhub/gitlab-ci/-/blob/master/LICENSE).

So first I'd want to ask which you want to site (the repo you commented on here or the gitlab-ci repo?) and then once we figure that out, I'll add a Zenodo. Then you need to add the correct license back to the code you've modified, and likely change the license to be appropriate. For both these cases, you can't just re-license under MIT which is less permissive.

Let me know your thoughts. Thanks for pinging me!

**Comment by garciagenrique** [comment]
OK, thanks for your answer. I have probably written and expressed myself very quickly.

Our project started from zero - why MIT was chosen. There are no copyright holders, so as far as I understood the license can be re-defined. In any case, I will need to include your BSD3 in our license (it is the gitlab-ci repo the one that I was meaning). For the citing, I was meaning just to cite the repository, not citing in a journal - sorry for the likely misunderstanding. 

I need to keep reading a bit in the subject as we are also working with  GNU GPL3 code.

**Comment by vsoch** [comment]
Yes, licensing is always a challenge! I think packaging the original BSD3 should work, and I'm not sure about GPL3 (you'll need to read up on that, let me know what you find!)

Generally, citing a repository == citing a DOI which is comparable to a journal. But if you are just casually mentioning it in a README or similar, including the license and then just linking to the repository is sufficient. Does that work?

**Comment by garciagenrique** [comment]
Hi vsoch, 

So what I have found so far is the following (extremely summarised):
 - BSD 3-clause and GNU GPLv3 are compatible - by compatible is meant that it can be combined code released with either licenses. 
 - However GPLv3 is 'parasite' - meaning that the resulting code must have the same license. Although it can be modified/distributed, changes must be stated. 

So if we do not 'mix' your code and the GPL one, our repository can contain adaptations of both original codes and be licensed under GPLv3. The parts that we will be using/adapting from your source code must contain the BDS license, though. 

I think it will be perfect if you create a zenodo doi; our code will potentially be used by other groups/institutes ;) - I will be linking to the repository in any case too.

**Comment by vsoch** [comment]
Sounds like a good plan, I've heard that about GPL too, so I tend to stay away from it (I try and use Mozilla 2.0 or MIT or (not as highly looked upon by industry) AGPL 3.0 for most of my work these days).

And here you go! https://zenodo.org/record/3834833. I really appreciate taking the time to give credit, even for such a little bit of code - if only all research software and recipes were treated so highly. The link is hugely appreciated as it might point other users to the recipe to help for their use case.

Let me know if I can be of any other help, otherwise feel free to close the issue.

**Comment by garciagenrique** [comment]
> And here you go! https://zenodo.org/record/3834833. I really appreciate taking the time to give credit, even for such a little bit of code - if only all research software and recipes were treated so highly. The link is hugely appreciated as it might point other users to the recipe to help for their use case.

That's perfect, thanks a lot vsoch ! I will be including the link in the repository for sure !
